### ISSUE TITLE
Base hawc2_vartrees on FUSED-Wind VTs

### ISSUE THREAD

**Issue by mrosemeier** [DTUWindEnergy/HAWC2Wrapper#8]
Is the intention of the HAWC2Wrapper to be interfaced with FUSED-Wind? If so, shouldn't the standard I/O vartrees such as HAWC2AirfoilPolar or HAWC2BeamStructure be based on AirfoilDataVT and BeamStructureVT?
I came across this issue when I used AirfoilPreppy and the HAWC2Wrapper connected via FUSED-Wind VTs to generate input files for HAWC2.

**Comment by fzahle** [comment]
As it is now only selected elements of HAWC2/HAWCStab2 are interfaced to FUSED-Wind I/O. I've so far only worked with the HAWCStab2 wrapper which implements a number of FUSED-Wind interfaces :

https://github.com/DTUWindEnergy/HAWC2Wrapper/blob/master/src/hawc2_wrapper/hawc2s_distributed.py#L93

geometry and beam structure inputs are read from a FUSED-Wind definition:

https://github.com/DTUWindEnergy/HAWC2Wrapper/blob/master/src/hawc2_wrapper/hawc2s_distributed.py#L210
https://github.com/DTUWindEnergy/HAWC2Wrapper/blob/master/src/hawc2_wrapper/hawc2s_distributed.py#L245

In the case of the airfoil data we've not yet had to update this on the fly so its unfortunately not been implemented yet. and there's a number of other variables that aren't properly hooked up to the FUSED-Wind definitions. 

It should be quick to adapt the geometry and beam hooks from the HAWC2S wrapper to the HAWC2 wrapper.
